{{- if not .Values.mas.matrix.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "matrix-authentication-service.fullname" . }}-initial-config-secret
stringData:
  config.yaml: |
    database:
      uri: "REPLACE_ME"
      max_connections: 10
      min_connections: 0
      connect_timeout: 30
      idle_timeout: 600
      max_lifetime: 1800

    matrix:
      homeserver: "{{ .Values.mas.matrix.homeserver }}"
      secret: "REPLACE_ME"
      endpoint: "{{ .Values.mas.matrix.endpoint }}"

    policy:
      data:
        admin_users: {{ .Values.mas.policy.data.admin_users }}

        admin_clients: {{ .Values.mas.policy.data.admin_clients }}

        client_registration:
          allow_host_mismatch: true
          allow_insecure_uris: true

        passwords:
          min_length: 16
          require_lowercase: true
          require_uppercase: true
          require_number: true

    upstream_oauth2:
      providers:
        - id: {{ .Values.mas.upstream_oauth2.providers.id }}

          issuer: {{ .Values.mas.upstream_oauth2.providers.issuer }}

          human_name: {{ .Values.mas.upstream_oauth2.providers.human_name }}

          brand_name: {{ .Values.mas.upstream_oauth2.providers.brand_name }}

          client_id: "REPLACE_ME"

          client_secret: "REPLACE_ME"

          token_endpoint_auth_method: {{ .Values.mas.upstream_oauth2.providers.token_endpoint_auth_method }}

          scope: {{ .Values.mas.upstream_oauth2.providers.scope }}

          discovery_mode: {{ .Values.mas.upstream_oauth2.providers.discovery_mode }}

          pkce_method: {{ .Values.mas.upstream_oauth2.providers.pkce_method }}

          authorization_endpoint: {{ .Values.mas.upstream_oauth2.providers.authorization_endpoint }}

          token_endpoint: {{ .Values.mas.upstream_oauth2.providers.token_endpoint }}

          jwks_uri: {{ .Values.mas.upstream_oauth2.providers.jwks_uri }}

          claims_imports:
            subject:
              template: {{ .Values.mas.upstream_oauth2.providers.claims_imports.subject.template }}

            localpart:
              #action: force
              template: {{ .Values.mas.upstream_oauth2.providers.claims_imports.localpart.template }}

            displayname:
              #action: suggest
              template: {{ .Values.mas.upstream_oauth2.providers.claims_imports.displayname.template }}

            email:
              #action: suggest
              template: {{ .Values.mas.upstream_oauth2.providers.claims_imports.email.template }}
              set_email_verification: {{ .Values.mas.upstream_oauth2.providers.claims_imports.email.set_email_verification }}
{{- end }}
