{{- if not .Values.existingMasConfigSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "matrix-authentication-service.fullname" . }}-initial-config-secret
stringData:
  config.yaml: |
    database:
      uri: "REPLACE_ME"
      max_connections: 10
      min_connections: 0
      connect_timeout: 30
      idle_timeout: 600
      max_lifetime: 1800

    clients:
      {{- range .Values.mas.clients }}
      - client_auth_method: {{ .client_auth_method }}
        client_id: {{ .client_id }}
        client_secret: {{ .client_secret }}
        {{- if .redirect_uris }}
        redirect_uris:
          {{- range .redirect_uris }}
          - {{ . }}
          {{- end }}{{/* end range redirect_uris */}}
        {{- end }}{{/* end if redirect_uris */}}
      {{- end }}{{/* end range clients */}}

    matrix:
      homeserver: "{{ .Values.mas.matrix.homeserver }}"
      secret: "REPLACE_ME"
      endpoint: "{{ .Values.mas.matrix.endpoint }}"

    policy:
      data:
        admin_users: {{ .Values.mas.policy.data.admin_users }}

        admin_clients: {{ .Values.mas.policy.data.admin_clients }}

        client_registration:
          allow_host_mismatch: true
          allow_insecure_uris: true

        passwords:
          min_length: 16
          require_lowercase: true
          require_uppercase: true
          require_number: true

    upstream_oauth2:
      providers:
        {{- range .Values.mas.upstream_oauth2.providers }}
        - authorization_endpoint: {{ .authorization_endpoint }}
          brand_name: {{ .brand_name }}
          claims_imports:
            displayname:
              action: {{ .claims_imports.displayname.action }}
              template: {{ .claims_imports.displayname.template }}
            email:
              action: {{ .claims_imports.email.action }}
              set_email_verification: {{ .claims_imports.email.set_email_verification }}
              template: {{ .claims_imports.email.template }}
            localpart:
              action: {{ .claims_imports.localpart.action }}
              template: {{ .claims_imports.localpart.template }}
            subject:
              template: {{ .claims_imports.subject.template }}
          client_id: {{ .client_id }}
          client_secret: {{ .client_secret }}
          human_name: {{ .human_name }}
          id: {{ .id }}
          issuer: {{ .issuer }}
          pkce_method: {{ .pkce_method }}
          scope: {{ .scope }}
          token_endpoint_auth_method: {{ .token_endpoint_auth_method }}
        {{- end }}{{/* end range providers */}}
{{- end }}
