{{- if not .Values.existingMasConfigSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "matrix-authentication-service.fullname" . }}-initial-config-secret
stringData:
  config.yaml: |
    database:
      uri: "REPLACE_ME"
      max_connections: 10
      min_connections: 0
      connect_timeout: 30
      idle_timeout: 600
      max_lifetime: 1800

    clients:
      {{- range .Values.mas.clients }}
      - {{ . | toYaml | indent 4 | trim }}
      {{- end }}

    matrix:
      homeserver: "{{ .Values.mas.matrix.homeserver }}"
      secret: "REPLACE_ME"
      endpoint: "{{ .Values.mas.matrix.endpoint }}"

    policy:
      data:
        admin_users: {{ .Values.mas.policy.data.admin_users }}

        admin_clients: {{ .Values.mas.policy.data.admin_clients }}

        client_registration:
          allow_host_mismatch: true
          allow_insecure_uris: true

        passwords:
          min_length: 16
          require_lowercase: true
          require_uppercase: true
          require_number: true

    upstream_oauth2:
      providers:
      {{- range .Values.mas.upstream_oauth2.providers }}
      - {{ . | toYaml | indent 4 | trim }}
      {{- end }}
{{- end }}
